#! /bin/bash

message "CREATE NEW TEMP SCHEMA"
$VSQL_BIN/vsql -h $VERTICA_HOST -p $VERTICA_PORT -U $VERTICA_USER -d $VERTICA_DB -c \
  "CREATE SCHEMA $TMPSCHEMA;
  SET search_path TO $TMPSCHEMA;
  GRANT ALL ON SCHEMA $TMPSCHEMA TO $VERTICA_USER;
  GRANT USAGE ON SCHEMA $TMPSCHEMA TO $VERTICA_USER;
  GRANT SELECT ON ALL TABLES IN SCHEMA $TMPSCHEMA TO $VERTICA_USER;
  COMMENT ON SCHEMA $TMPSCHEMA IS 'temporary refresh schema';" 1>>$STDOUT 2>>$STDERR

##### 5. Load schema file into TMPSCHEMA
$VSQL_BIN/vsql -h $VERTICA_HOST -p $VERTICA_PORT -U $VERTICA_USER -d $VERTICA_DB -f $SCHEMADIR/schema_final.sql 1>>$STDOUT 2>>$STDERR
