#! /bin/bash

for schema in $SCHEMAS
do
    TMPACCTSCHEMA=$schema\_$TMPSCHEMA

    message "CREATE NEW TEMP SCHEMA FOR $schema"

    echo "CREATE SCHEMA $TMPACCTSCHEMA;
    SET search_path TO $TMPACCTSCHEMA;
    GRANT ALL ON SCHEMA $TMPACCTSCHEMA TO $RSUSER;
    GRANT USAGE ON SCHEMA $TMPACCTSCHEMA TO $RSUSER;
    GRANT SELECT ON ALL TABLES IN SCHEMA $TMPACCTSCHEMA TO $RSUSER;
    COMMENT ON SCHEMA $TMPACCTSCHEMA IS 'temporary refresh schema';" | cat - $SCHEMADIR/schema_final.sql > $SCHEMADIR/schema_final_temp.sql

    $PGSQL_BIN/psql -h $RSHOST -p $RSHOSTPORT -U $RSADMIN -d $RSNAME -f $SCHEMADIR/schema_final_temp.sql 1>>$STDOUT 2>>$STDERR
done
